nelmio_cors:
    defaults:
        allow_origin: ['http://127.0.0.1:8000'] # Remplacez par l'adresse de votre domaine local
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/': # Chemin de votre API, ici tous les chemins sont couverts
            allow_origin: ['*'] # Vous pouvez ajuster cette valeur selon vos besoins
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type']
            max_age: 3600
            hosts: []
            origin_regex: false
            forced_allow_origin_value: ~
